[package]
name = "crossref"
version = "0.1.0"
authors = ["David Pascoe-Deslauriers <dpascoed@coldfrontlabs.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
lto = true
panic = 'abort'
